spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB #单个文件上传最大体积
      max-request-size: 3000MB
      #windows路径
      location: E:\UploadFile\
      #Linux路径
      #location: d:/restaurantRes
      
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效
server:
   port: 443
   custom:
      httpPort: 80
      port: 443
#https加密端口号 443
#SSL证书路径，文件名修改成你自己的 一定要加上classpath:
   ssl:
      key-store: classpath:www.pipo.vip.jks
#SSL证书密码，申请时填写的
      key-store-password: 199407
#证书类型
      key-store-type: JKS


#服务域名
yuming: http://localhost:8080/

#上传文件的Linux路径
#WebPath: /opt/
#上传文件的windows路径
#WebPath: E:\UploadFile\

#映射路径
WebServer: restaurantRes/

